gui:
  showIcons: true
  theme:
    lightTheme: false
    activeBorderColor:
      - "#ff5a00"
      - bold
    selectedLineBgColor:
      - "#313244"
    selectedRangeBgColor:
      - "#ff5a00"
      - bold
    unstagedChangesColor:
      - yellow
quitOnTopLevelReturn: true
