#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_origin_display        default
yabai -m config window_placement             second_child
yabai -m config window_shadow                on
yabai -m config window_opacity               off
yabai -m config split_ratio                  0.75
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               cmd
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   09

# By default, open new windows in a float at the center of the screen
yabai -m rule --add app="." manage=off grid=8:6:1:1:4:6

# exclusions
yabai -m rule --add app="^System Settings$" manage=off grid=8:8:2:2:4:4
yabai -m rule --add app="^Finder$" manage=off grid=8:8:2:2:4:4
yabai -m rule --add app="^Stats$" manage=off
yabai -m rule --add app="^Lunar$" manage=off
yabai -m rule --add app="^Arc$" title="^Picture in Picture$" manage=off
yabai -m rule --add app="^Fantastical Helper$" manage=off
yabai -m rule --add app="^Loom$" manage=off
yabai -m rule --add app="^Cardhop$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^demo_" manage=off  # demos and Processing stuff
