[[input.prepend_keymap]]
on   = "<Esc>"
run  = "close"
desc = "Cancel input"

[[manager.prepend_keymap]]
on   = "!"
run  = 'shell "$SHELL" --block'
desc = "Open shell here"

[[manager.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
desc = "Go to git root"

[[manager.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'
desc = "Preview with macOS quick look"
